{{ if .Values.jaeger.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldrule-jaeger-ingress
spec:
  rules:
    - host: {{ .Values.jaeger.url }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shieldrule-api-service
                port:
                  number: 8000
{{ end }}