apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldrule-api-ingress
  annotations:
    {{- range $k, $v := .Values.api.ingress.annotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.api_url}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shieldrule-api-service
                port:
                  number: 8000
{{ if .Values.deploy_grpc }}
    - host: {{ .Values.grpc_url}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shieldrule-api-service
                port:
                  number: 9520
{{ end }}