# Used to set the managed cert and ingress for the web service
web_url:
# Used to set the managed cert and ingress for the api service
api_url:
# Used to set the managed cert and ingress for the api GRPC service
grpc_url: