apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldrule-web-ingress
  annotations:
    {{- range $k, $v := .Values.web.ingress.annotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  rules:
    - host:  {{ .Values.web_url }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shieldrule-web-service
                port:
                  number: 8000