{{- if .Values.web.horizontalPodAutoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shieldrule-web
spec: {{ .Values.web.horizontalPodAutoscaling.spec | toYaml | trim | nindent 2 }}
{{ end }}