apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shieldrule-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shieldrule-web
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50