apiVersion: v1
kind: Service
metadata:
  name: shieldrule-web-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:600592424179:certificate/cad13840-e12f-4bea-b153-4f658c612a66
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: NodePort
  selector:
    app: shieldrule-web
  ports:
    - port: 8000
      targetPort: 8000
      name: web