{{ if .Values.jaeger.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: badger-strategies
data:
  strategies.json: |
    {
      "service_strategies": [
        {
          "service": "sliderule-api",
          "type": "probabilistic",
          "param": 0.8,
          "operation_strategies": [
            {
              "operation": "GET /actuator/health",
              "type": "probabilistic",
              "param": 0.0
            },
            {
              "operation": "GET /actuator/prometheus",
              "type": "probabilistic",
              "param": 0.0
            }
          ]
        }
      ],
      "default_strategy": {
        "type": "probabilistic",
        "param": 0.5,
        "operation_strategies": [
          {
            "operation": "/health",
            "type": "probabilistic",
            "param": 0.0
          },
          {
            "operation": "/metrics",
            "type": "probabilistic",
            "param": 0.0
          }
        ]
      }
    }

{{ end }}