{{ if .Values.jaeger.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sliderule-jaeger
spec:
  replicas: 1
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: sliderule-jaeger
      role: sliderule-jaeger-role
  strategy: { }
  template:
    metadata:
      labels:
        app: sliderule-jaeger
        role: sliderule-jaeger-role
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - image: "jaegertracing/all-in-one:1.53"
          imagePullPolicy: Always
          name: sliderule-jaeger
          volumeMounts:
            - mountPath: /badger
              name: badger
            - name: badger-strategies
              mountPath: /badger/strategies.json
              subPath: strategies.json
          env:
            - name: "OTEL_SERVICE_NAME"
              value: "sliderule-backend"
            - name: "OTEL_TRACES_EXPORTER"
              value: "jaeger"
            - name: "OTEL_METRICS_EXPORTER"
              value: "none"
            - name: "OTEL_EXPORTER_JAEGER_ENDPOINT"
              value: "http://jaeger:14250"
            - name: "SPAN_STORAGE_TYPE"
              value: "badger"
            - name: "BADGER_EPHEMERAL"
              value: "false"
            - name: "BADGER_DIRECTORY_VALUE"
              value: "/badger/data"
            - name: "BADGER_DIRECTORY_KEY"
              value: "/badger/key"
            - name: "BADGER_SPAN_STORE_TTL"
              value: "72h0m0s"
            - name: "SAMPLING_STRATEGIES_FILE"
              value: "/badger/strategies.json"
            - name: "COLLECTOR_ZIPKIN_HOST_PORT"
              value: "9411"
          ports:
            - containerPort: 16686
            - containerPort: 5778
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            timeoutSeconds: 10
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            timeoutSeconds: 10
            initialDelaySeconds: 15
            successThreshold: 3
          resources:
            requests:
              memory: 2048Mi
              cpu: 512m
            limits:
              memory: 2048Mi
              cpu: 512m
          securityContext:
            capabilities:
              drop:
                - all
      volumes:
        - name: badger
          emptyDir:
            sizeLimit: 500Mi
        - name: badger-strategies
          configMap:
            name: badger-strategies
      restartPolicy: Always
status: { }

{{ end }}