{{ if .Values.jaeger.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sliderule-jaeger
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sliderule-jaeger
  minReplicas: {{ .Values.web.count }}
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
{{ end }}