{{ if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  selector:
    app: sliderule-jaeger
  ports:
    - port: 16686
      targetPort: 16686
      name: jaeger-ui
    - port: 14250
      targetPort: 14250
      name: jaeger
{{ end }}