{{ if .Values.service_account_role }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: tasks
  name: tasks
  namespace: {{ .Values.SHIELDRULE_ENVIRONMENT }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.service_account_role }}
{{ end }}