kind: PersistentVolume
apiVersion: v1
metadata:
  name: sliderule-quickdemo-postgres-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldrule-db
spec:
  replicas: 1
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: shieldrule-db
      role: shieldrule-db-role
  strategy: { }
  template:
    metadata:
      labels:
        app: shieldrule-db
        role: shieldrule-db-role
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: postgres
          image: postgres:15.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-claim

status: { }
