{{- if .Values.is_gcp }}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-grpc-backend
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 9520
    type: HTTP/2
    requestPath: /

{{- end }}