{{- if .Values.api.horizontalPodAutoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shieldrule-api
spec: {{ .Values.api.horizontalPodAutoscaling.spec | toYaml | trim | nindent 2 }}
{{ end }}