apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}
  PROMETHEUS_ACCESS_TOKEN: {{ .Values.PROMETHEUS_ACCESS_TOKEN | b64enc | quote }}
