{{ if .Values.api.add_secret }}

apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}
  AUTH_CLIENT_ID: {{ .Values.AUTH_CLIENT_ID | quote }}
  AUDIENCE_URL: {{ .Values.AUDIENCE_URL | quote }}
  READ_ONLY_POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc | quote }}
  READ_ONLY_POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}

{{ end }}