apiVersion: v1
kind: Service
metadata:
  name: shieldrule-api-service
  annotations:
    {{- range $k, $v := .Values.api.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- if .Values.is_gcp }}
    cloud.google.com/backend-config: '{"default": "api_grpc_backend"}'
    {{- end }}
spec:
  type: NodePort
  selector:
    app: shieldrule-api
  ports:
    - name: {{ .Values.api.service.name }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      nodePort: {{ .Values.api.service.nodePort }}
      protocol: {{ .Values.api.service.protocol }}
    - port: 9520
      targetPort: 9520
      name: grpc
