apiVersion: v1
kind: Service
metadata:
  name: shieldrule-api-service
  annotations:
    {{- range $k, $v := .Values.api.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- if .Values.is_gcp }}
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"9520":{}}}'
    cloud.google.com/backend-config: '{"ports": {"grpc":"api-grpc-backend"}}'
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: shieldrule-api
  ports:
    - name: {{ .Values.api.service.name }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: {{ .Values.api.service.protocol }}
    - port: 9520
      targetPort: 9520
      name: grpc
