apiVersion: v1
kind: Service
metadata:
  name: shieldrule-api-service
spec:
  type: NodePort
  selector:
    app: shieldrule-api
  ports:
    - name: {{ .Values.api.service.name }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      nodePort: {{ .Values.api.service.nodePort }}
      protocol: {{ .Values.api.service.protocol }}
    - port: 9520
      targetPort: 9520
      name: grpc
