apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sliderule-secret
  namespace: {{ .Values.target_namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sliderule-secretstore
    kind: ClusterSecretStore
  target:
    name: sliderule-secret
    creationPolicy: Owner
  dataFrom:
    - key: sliderule_secret