apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sliderule-secret
  namespace: {{ .Values.target_namespace }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: sliderule-secretstore
    kind: SecretStore
  target:
    name: sliderule-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.api.secret.name }}


---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sliderule-web-secret
  namespace: {{ .Values.target_namespace }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: sliderule-secretstore
    kind: SecretStore
  target:
    name: sliderule-web-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.web.secret.name }}