apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sliderule-secretstore
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.project_id }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.cluster_location }}
          clusterName: {{ .Values.cluster_name }}
          serviceAccountRef:
            name: {{ .Values.service_account_name }}
            namespace: {{ .Values.namespace }}