apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sliderule-secretstore
  namespace: {{ .Values.target_namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.project_id }}