{{ if .Values.api_service_account_name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api_service_account_name }}
  annotations:
    {{ if .Values.aws_service_account_iam_role }}
    eks.amazonaws.com/role-arn: {{ .Values.aws_service_account_iam_role }}
    {{ end }}
{{ end }}