apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sliderule-psp
spec:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  runAsUser:
    rule: 'MustRunAsNonRoot'
  volumes:
    - '*'