{{ if .Values.deploy_jobs }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shieldrule-jobs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shieldrule-jobs
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
{{ end }}