{{ if .Values.enable_aws_alb }}
{{ if .Values.deploy_jobs }}

apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: jobs-tgb
spec:
  serviceRef:
    name: shieldrule-jobs-service
    port: 8000
  targetGroupARN: {{ .Values.jobs_tg_arn }}
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: {{ .Values.alb_sg_id }}
        ports:
          - port: 8000
          - port: 9520

{{ end }}
{{ end }}