{{ if .Values.deploy_jobs }}
apiVersion: v1
kind: Service
metadata:
  name: shieldrule-jobs-service
spec:
  type: NodePort
  selector:
    app: shieldrule-jobs
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.ports.jobs }}
      name: api
    - port: 9520
      targetPort: 9520
      name: grpc
{{ end }}