apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: shieldrule-cert
spec:
  domains:
    - {{ .Values.api_url }}
    - {{ .Values.web_url }}
{{ if .Values.grpc_url }}
    - {{ .Values.grpc_url }}
{{ end }}